# Generated by Django 5.0.3 on 2026-03-15 04:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlertGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='分组名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='分组描述')),
                ('match_rules', models.JSONField(default=dict, help_text='告警标签匹配规则，JSON格式', verbose_name='匹配规则')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '告警分组',
                'verbose_name_plural': '告警分组',
                'db_table': 'alert_group',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Receiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='姓名')),
                ('receive_type', models.CharField(choices=[('email', '邮件'), ('webhook', 'Webhook'), ('dingtalk', '钉钉'), ('wechat', '企业微信'), ('slack', 'Slack')], default='email', max_length=20, verbose_name='接收方式')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='邮箱地址')),
                ('webhook_url', models.URLField(blank=True, null=True, verbose_name='Webhook地址')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='手机号')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '接收人',
                'verbose_name_plural': '接收人',
                'db_table': 'alert_receiver',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AlertHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_name', models.CharField(max_length=200, verbose_name='告警名称')),
                ('severity', models.CharField(default='warning', max_length=20, verbose_name='严重级别')),
                ('message', models.TextField(verbose_name='告警信息')),
                ('labels', models.JSONField(default=dict, verbose_name='标签')),
                ('status', models.CharField(choices=[('firing', '告警中'), ('resolved', '已恢复')], default='firing', max_length=20, verbose_name='状态')),
                ('fired_at', models.DateTimeField(verbose_name='触发时间')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='恢复时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('alert_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='alert.alertgroup', verbose_name='告警分组')),
            ],
            options={
                'verbose_name': '告警历史',
                'verbose_name_plural': '告警历史',
                'db_table': 'alert_history',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='alertgroup',
            name='receivers',
            field=models.ManyToManyField(blank=True, related_name='alert_groups', to='alert.receiver', verbose_name='接收人'),
        ),
    ]
